# Generated by Django 3.0.6 on 2020-05-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SonnetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=200)),
                ('sonnet_nb', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
            options={
                'verbose_name_plural': 'sonnets',
            },
        ),
    ]
